version: '3.8'

services:
  directus:
    image: directus/directus:latest
    container_name: fashion-way-directus
    ports:
      - "8055:8055"
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      ADMIN_EMAIL: 'admin@fashion-way.de'
      ADMIN_PASSWORD: 'admin123'
      PUBLIC_URL: 'http://localhost:8055'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000,http://127.0.0.1:5500,http://localhost:5500'
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
    restart: unless-stopped 